### ISSUE TITLE
Doesn't work with terminal in vim8

### ISSUE THREAD

**Issue by karoliskoncevicius** [KKPMW/vim-sendtowindow#2]
In vim the terminal by default is not put into *normal* mode. And when it is - the buffer is still not modifiable. Need to investigate and fix it.

**Comment by sgiavi** [comment]
Hi KKPMW,
Thank you for this plugin, it seems to be EXACTLY what I need for my R programming! Unfortunately I upgraded to Vim 8.1 because it was required by another plugin claiming to solve the "working with R in Vim" issue but it was a big disappointment. Now, I don't mind to have the newest Vim version, I just want to be able to work with R and use the vim-sendtowindow plugin. How can I downgrade my Vim??
Thank you so much for sharing your work,
Cheers,
SG

**Comment by karoliskoncevicius** [comment]
Hello SG,

As you can see this plugin currently is not working in vim. This issue is here now for a bit too long and I really should get to it and fix this. But I am not sure if I will be able to find time for doing so in the following week.

What you can do to get this working, meantime, is to use neovim, if you are open to this kind of suggestion. I myself am using neovim now and never had problems with this plugin in any of neovim's versions with `:terminal`.

**Comment by sgiavi** [comment]
Hello KKPMW,

Thank you for you quick answer. I was wondering whether your plugin is working on previous version of Vim, like the 7.4, and if it would be meaningful for me to downgrade to that lower version in order to take advantage of vim-sendtowindow. However, I tried to downgrade but it seems more tricky than I expected.

I probably will give a try to neovim, even if I can get more used to program R in Vim using the Vim simulator in Rstudio while waiting for you to fix that bug. Looking forward to that :-)

Cheers,
SG

**Comment by sgiavi** [comment]
Hello KKPMW,

Thank you for you quick answer. I was wondering whether your plugin is working on previous version of Vim, like the 7.4, and if it would be meaningful for me to downgrade to that lower version in order to take advantage of vim-sendtowindow. However, I tried to downgrade but it seems more tricky than I expected.

I probably will give a try to neovim, even if I can get more used to program R in Vim using the Vim simulator in Rstudio while waiting for you to fix that bug. Looking forward to that :-)

Cheers,
SG

**Comment by sgiavi** [comment]
Hello again,
I downloaded neovim and indeed it looks as it works.
Anyway, I really would like to help fixing the plugin issue if I had the least idea about how writing a plugin works. I have read about a way to put (paste) text in non-normal mode, but if the terminal buffer is not modifiable there is a major problem to investigate... 
Have a nice week,
SG

**Comment by karoliskoncevicius** [comment]
Hello again @sgiavi 

The plugin should now be working in vim `:terminal` buffer. Fixed with this commit: https://github.com/KKPMW/vim-sendtowindow/commit/c9a91f32aa0c83282a5db465dcce1376a6eb1b87

Maybe you could check and confirm? For now it's only tested on my machine with vim 8.1.577

**Comment by sgiavi** [comment]
Hi KKPMW!
I have Vim 8.1.1332 and I'm afraid it doesn't work, not in the way it does in Neovim (I tried there and it works nicely).
Cheers,
Sgiavi

**Comment by karoliskoncevicius** [comment]
Hmmm that is quite weird. Did you update the plugin?

My vim version is a bit older, but not sure why it shouldn't be working with a slightly newer version. Will have to investigate again. But just please confirm that the plugin is updated.

**Comment by karoliskoncevicius** [comment]
Hello again @sgiavi 

Just compiled the newest version of vim and it seems to be working for me.

Are you able to send text from one non-terminal window to another non-terminal window? If not then that would suggest the plugin isn't installed properly.

**Comment by sgiavi** [comment]
I use Plug-Vim as plugin manager, I opened vim and ran :PlugUpdate. It told me that sendtowindow is up to date. It works from non-terminal to non-terminal window, but not on terminal window. But maybe I'm missing something else, so maybe let try someone else too.

**Comment by karoliskoncevicius** [comment]
Hmm weird. I think you are using the same plugin manager I do. Here is what you can try:

1. Determine your plugin directory. Should be on the line `call plug#begin(...)` in your vimrc.
2. Go to that directory and detect the `vim-sendtowindow` plugin
3. Open the file `plugin/sendtosplit.vim`
4. The lines 34-35 should be:

```
      call term_sendkeys('', @0)
      call term_sendkeys('', "\r")
```

If not - the plugin is not updated. If yes - then it is not working for some reason...

**Comment by sgiavi** [comment]
I have those lines

**Comment by karoliskoncevicius** [comment]
Maybe you can try one more thing?

```
    :source /directory/to/vimplug/vim-sendtowindow/plugin/sendtosplit.vim
```

And then see if it works...

**Comment by karoliskoncevicius** [comment]
In addition another possibility is that some other plugins get in the way somehow. Unlikely but worth testing I think. For that you can create a temporary `.vimrc` file that has nothing in it except this plugin and see if then it works?

```
   vim -u NONE
   :source /directory/to/vimplug/vim-sendtowindow/plugin/sendtosplit.vim
```

Sorry, just bounding ideas off. Not really sure what is going on.

**Comment by sgiavi** [comment]
I did it. Now the code is sent to the terminal window, but to see it I have to move the cursor on the terminal and enter insert mode.

**Comment by karoliskoncevicius** [comment]
Hmm that shouldn't be the case (and the text appears instantly, at least for me).

What did you do to make it work on your end, what was the problem?

**Comment by sgiavi** [comment]
the last change you suggested:

vim -u NONE
:source /directory/to/vimplug/vim-sendtowindow/plugin/sendtosplit.vim

**Comment by karoliskoncevicius** [comment]
If it works with `vim -u NONE` (not loading any configuration files) and doesn't work normally it might suggest that you have other settings that change the behaviour somehow. Are you using a lot of plugins? Maybe some of them adjust the way terminal buffers work?

Not sure what to suggest. Will try to run vim on another machine and look if it works there. For the record - what system are you on? MAC OS / linux / windows ?

**Comment by karoliskoncevicius** [comment]
Hello, I checked this on another machine and it seems to be working there as well. You also confirmed that the text is sent to terminal, but in your case it's not displayed until you enter insert mode in its window.

Therefore I would like to close this issue. However feel free to open another issue about the remaining problems you have, if they are not solved yet.

**Comment by shabbychef** [comment]
I have this issue as well: I can send text to another terminal, but it does not appear in the terminal until I switch focus and hit return.  I know the text is sent because I can send cod to a REPL that causes a plot to appear. 

I am not able to get the plugin to work via `vim -u NONE`. Perhaps because I install via Bundle?

**Comment by karoliskoncevicius** [comment]
Hello @shabbychef,

To clarify - is the plugin working for you or not? I am a bit confused because you first said it works and you can send code and get the plot to appear, but then you said that you are not able to get the plugin to work. Can you give me more details about your current issue and clarify?

**Comment by shabbychef** [comment]
Sorry for being unclear: the plugin _does_ send the text to terminal/other window. I know this because sending plotting commands to a REPL causes the plot to appear. However, the sent text does not appear in the terminal window unless I change focus and move to the other window. I have this issue both when the terminal is running a bare REPL or is running a REPL within screen. This is under vim 9.0 on a mac laptop, if that means anything.

**Comment by karoliskoncevicius** [comment]
But once you go to the terminal to gain focus and then return back to your buffer, the next time you send text the issue is no longer there, right?

**Comment by shabbychef** [comment]
The issue is that the terminal window does not update to _show_ the text that has been sent over.
I just installed the [habamax/vim-sendtoterm](https://github.com/habamax/vim-sendtoterm) plugin as a test, and it has the same issue.
So potentially the problem is that my terminal mode does not properly update to show newly inserted text?
That is, it's probably a `vim` problem and not a plugin problem...

**Comment by karoliskoncevicius** [comment]
I have the same issue too, I've never found how to resolve it. However it goes away after you focus the terminal buffer once. For me it's like this: send text to the terminal buffer, the text goes off-screen, I navigate to the terminal buffer and enter terminal insert mode, the text at the bottom is now visible, I escape to normal mode, go back to my buffer, and from this time onwards the text sent to terminal is now visible and this issue is no longer there.

If that works the same for you then yeah - I have this too. I wish I knew the cause of it and how to solve it. But yeah, it's not an issue of vim-sendtowindow, it happens with all the terminal buffers in both Vim and NeoVim.

**Comment by shabbychef** [comment]
I see. I have been using the `vim-conque` plugin for 10+ years now and was quite happy with it, but it can be a pain to get installed, and I wanted to move to something modern using the built-in terminal. I have seen some hints [here](https://www.reddit.com/r/neovim/comments/qus8yf/neovim_terminal_not_updatingrefreshing_unless_im/) that I will follow up on.
