### ISSUE TITLE
An extra carriage return when sending a visual line selection

### ISSUE THREAD

**Issue by SultanOrazbayev** [KKPMW/vim-sendtowindow#6]
Thank you for this useful plugin!

This is a minor bug, but when I select a text inside a file with `Shift+V` (visual line selection) and then send it to a right window with `<space>l`, the other window appears to receive one additional carriage return symbol.

Specifically, when I am sending the text to an IPython running in a right window, I get a blank cell after the correctly sent text. Note this doesn't appear if I use a regular motion (e.g. `<space>l + $` doesn't have this problem).

Edit: the problem is likely that visual line selection also copies the new line break, so maybe this is not a bug, but it might be worth it to trim/drop the last line break in a copied text that is sent to another window.

**Comment by karoliskoncevicius** [comment]
Hello,

Thank you for interest in the plugin and reporting on this issue. Indeed I consider this a minor bug, as you put it. I did not catch it because I never use visual selection for sending lines of text.

Instead of `<space>l + $` I do `<space>l + _` and it works from anywhere within the line.\
And and top of that - unlike visual selection - it is dot-repeatable (`<sapce>l + _`, `.`, `.`, `.`).

However the behaviour with visual line should now be fixed in this commit: https://github.com/KKPMW/vim-sendtowindow/commit/1990cd75acfece6e610e8de463e9bfadc366b43a .\
Simply update or reinstall the plugin.

Thanks again, and let me know if you will encounter further issues with this.

P.S. Please note that this plugin will add an extra line (for execution) when sending parts of line to the terminal. But only when sending to the terminal.

**Comment by SultanOrazbayev** [comment]
Thank you!
